課題3 for fix/16
iamyabui/lamp_practice pull request #18
Opened 2020-01-19 15:02 UTC by iamyabui

post部分のissueコメントについては反映がまだですが、それ以外の実装については編集してみました。レビューをお願いいたします。

2020-01-20 06:38 UTC, thisprodigiousgeek commented on www/model/detail.php
> +function get_order($db, $order_id){
detail.phpにorderを取得する処理が書かれているのは不自然ですね！

2020-01-20 06:40 UTC, thisprodigiousgeek commented on www/model/order.php
> +function sum_orders($db, $order_id){
合計金額を求めるために再度orderからデータを取得するのは非効率ですね！get_user_ordersで同時に合計金額も求めてしまいましょう！

2020-01-20 06:40 UTC, thisprodigiousgeek commented on www/model/order.php
> +function get_admin_orders($db){
get_user_ordersと共通点が多いので、現状では非効率ですね！

2020-01-20 06:41 UTC, thisprodigiousgeek commented on www/view/detail_view.php
> +      <?php if(count($details) > 0){ ?>
インデントを修正しておきましょう。

2020-01-20 06:41 UTC, thisprodigiousgeek commented on www/view/order_view.php
> +      <?php if(count($orders) > 0){ ?>
こちらもインデントを修正しましょう。

2020-01-20 06:42 UTC, thisprodigiousgeek commented on www/view/order_view.php
> +              <form method="post" action="detail.php">
detail.phpを表示させるためにpostを用いるのは不自然ですね！

2020-01-20 06:44 UTC, thisprodigiousgeek commented on www/html/detail.php
> +$orders = get_order($db, $order_id);
$ordersにorderが一件だけ入っている状態は不自然ですね！

2020-01-20 06:45 UTC, thisprodigiousgeek requested changes
まずは、しっかり大枠を組み立てていただけましたね！
コメントを参考に修正を行いましょう。
getとpostの違いについても、しっかり調べてみましょう！

2020-01-20 09:42 UTC, iamyabui commented on www/model/detail.php
> +function get_order($db, $order_id){
get_orderをorder.phpに記載すればよろしいでしょうか。

2020-01-20 09:56 UTC, iamyabui commented on www/model/order.php
> +function get_admin_orders($db){
get_admin_orders関数内でif分を使用しadminユーザとadminユーザ出ない場合の抽出条件を変更するようにすればよろしいでしょうか。


```
function get_admin_orders($db, $user){
    $sql = "
    SELECT
        order_id,
        created
    FROM
        orders
    ORDER BY
        created DESC
    ";
    //ユーザがadminでない場合、ユーザのorder情報のみ取得する。
  if(is_admin($user) === false){
    $sql .= '
      WHERE user_id = :user_id
    ';
    $params = array(':user_id' => $user);
    return fetch_all_query($db, $sql, $params);
  }
    return fetch_all_query($db, $sql);
}
```

2020-01-20 10:00 UTC, iamyabui commented on www/view/detail_view.php
> +      <?php if(count($details) > 0){ ?>
22行目を一つ引っ込めます。

2020-01-20 10:01 UTC, iamyabui commented on www/view/order_view.php
> +      <?php if(count($orders) > 0){ ?>
16行目を引っ込めました。

2020-01-20 10:36 UTC, iamyabui commented on www/model/order.php
> +function sum_orders($db, $order_id){
returnでただ値を返すところを変数に入れてしまって、あとは合計金額を計算する式をいれていく感じでしょうか。

```
function get_user_orders($db, $user){
    $sql = "
    SELECT
        order_id,
        created
    FROM
        orders
    WHERE
        user_id = :user_id
    ORDER BY
        created DESC
    ";
    $params = array(':user_id' => $user);
    $details = fetch_all_query($db, $sql, $params);
    $total_price = 0;
    foreach($details as $detail){
        $total_price += $detail['price_bought'] * $detail['amount'];
    }
    return $total_price;
}
```

2020-01-20 10:38 UTC, iamyabui commented on www/html/detail.php
> +$orders = get_order($db, $order_id);
$ordersを$orderに変数名を変えたほうがいいということでしょうか。

2020-01-20 10:45 UTC, iamyabui commented on www/view/order_view.php
> +              <form method="post" action="detail.php">
postはurl上に渡す値の情報が載らないため、隠す必要のある情報は使用する。
getは検索結果を表すページに使われるので、今回detail.phpは明細の結果を表示するページで、二回目以降から高速で表示されるようになる利点から、getを使用するのがふさわしいといことでしょうか？

2020-01-20 12:52 UTC, iamyabui commented
修正が完了しましたのでpushしました！ご確認よろしくおねがいします。

2020-01-22 09:48 UTC, thisprodigiousgeek requested changes
すみません、コメントがPending状態になっておりました。
あとわずかですので、レッスン内で完成させましょう！

2020-01-22 09:48 UTC, thisprodigiousgeek commented on www/html/detail.php
>  if(is_valid_csrf_token($token) === false){
postで取得しているわけではないので、CSRFのトークン照合は不要ですね！

2020-01-22 09:48 UTC, thisprodigiousgeek commented on www/html/detail.php
>      redirect_to(ORDER_URL);
リダイレクトの前にエラーメッセージを追加しておきましょう！

2020-01-22 12:16 UTC, iamyabui commented
最終修正と、稼働確認が完了しましたのでマージをお願いいたします。

2020-01-23 05:50 UTC, thisprodigiousgeek approved these changes
はい、こちらでバッチリですね！マージさせていただきます。

2020-01-23 05:50 UTC, merged